basePath: /v1
definitions:
  models.CommentCreateReq:
    properties:
      comment:
        type: string
      post_id:
        type: string
      user_id:
        type: string
    type: object
  models.CommentFindResponse:
    properties:
      comments:
        items:
          $ref: '#/definitions/models.CommentResponse'
        type: array
      count:
        type: integer
    type: object
  models.CommentResponse:
    properties:
      comment:
        type: string
      created_at:
        type: string
      id:
        type: string
      post_id:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.CommentUpdateReq:
    properties:
      comment:
        type: string
      id:
        type: string
      user_id:
        type: string
    type: object
  models.MediaResponse:
    properties:
      body:
        $ref: '#/definitions/models.UploadPhotoRes'
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  models.OtpCheckResponse:
    properties:
      body:
        properties:
          is_right:
            type: boolean
        type: object
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  models.PostCreateReq:
    properties:
      content:
        type: string
      slug:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  models.PostFindResponse:
    properties:
      count:
        type: integer
      posts:
        items:
          $ref: '#/definitions/models.PostResponse'
        type: array
    type: object
  models.PostResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      slug:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.PostUpdateReq:
    properties:
      content:
        type: string
      id:
        type: string
      slug:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  models.StandardResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  models.UploadPhotoRes:
    properties:
      photo_url:
        type: string
    type: object
  models.UserApiUpdateReq:
    properties:
      user_name:
        type: string
    type: object
  models.UserCheckRes:
    properties:
      status:
        type: string
    type: object
  models.UserForgotPasswordVerifyReq:
    properties:
      new_password:
        type: string
      otp:
        type: string
      user_name_or_email:
        type: string
    type: object
  models.UserLoginRequest:
    properties:
      password:
        type: string
      user_name_or_email:
        type: string
    type: object
  models.UserRegisterReq:
    properties:
      email:
        type: string
      fullname:
        type: string
      otp:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  models.UserResponse:
    properties:
      access_token:
        type: string
      created_at:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        type: string
      password:
        type: string
      refresh_token:
        type: string
      updated_at:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: Here QA can test and frontend or mobile developers can get information
    of API endpoints.
  title: Monolithic project API Endpoints
  version: "1.0"
paths:
  /comment:
    post:
      consumes:
      - application/json
      description: Here comment can be created.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.CommentCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Create comment
      tags:
      - Comment
    put:
      consumes:
      - application/json
      description: Here comment can be updated.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.CommentUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Update comment
      tags:
      - Comment
  /comment/{id}:
    delete:
      consumes:
      - application/json
      description: Here comment can be deleted.
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandardResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Delete comment
      tags:
      - Comment
    get:
      consumes:
      - application/json
      description: Here comment can be got.
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Get comment by key
      tags:
      - Comment
  /comment/list:
    get:
      consumes:
      - application/json
      description: Here all comments can be got.
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: order_by_created_at
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: post_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommentFindResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Get comments list
      tags:
      - Comment
  /media/photo:
    post:
      consumes:
      - multipart/form-data
      description: Through this api frontent can upload photo and get the link to
        the media.
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MediaResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Upload media
      tags:
      - Media
  /post:
    post:
      consumes:
      - application/json
      description: Here post can be created.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.PostCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Create post
      tags:
      - Post
    put:
      consumes:
      - application/json
      description: Here post can be updated.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.PostUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Update post
      tags:
      - Post
  /post/{id}:
    delete:
      consumes:
      - application/json
      description: Here post can be deleted.
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandardResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Delete post
      tags:
      - Post
    get:
      consumes:
      - application/json
      description: Here post can be got.
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Get post by key
      tags:
      - Post
  /post/list:
    get:
      consumes:
      - application/json
      description: Here all posts can be got.
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: order_by_created_at
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostFindResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Get posts list
      tags:
      - Post
  /user:
    delete:
      consumes:
      - application/json
      description: Here user can be deleted, user_id is taken from token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandardResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Here user can be registered.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Register user
      tags:
      - User Authorzation
    put:
      consumes:
      - application/json
      description: Here user can be updated.
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.UserApiUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - User
  /user/check/{email}:
    get:
      consumes:
      - application/json
      description: Here user status is checked. If user is exists in database it should
        be logged in else registered
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserCheckRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Check User status
      tags:
      - User Authorzation
  /user/forgot-password/{user_name_or_email}:
    get:
      consumes:
      - application/json
      description: Through this api user forgot  password can be enabled.
      parameters:
      - description: user_name_or_email
        in: path
        name: user_name_or_email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandardResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: User forgot password
      tags:
      - User Authorzation
  /user/forgot-password/verify:
    post:
      consumes:
      - application/json
      description: Through this api user forgot  password can be enabled.
      parameters:
      - description: User Login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserForgotPasswordVerifyReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandardResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: User forgot password
      tags:
      - User Authorzation
  /user/login:
    post:
      consumes:
      - application/json
      description: Through this api user is logged in
      parameters:
      - description: User Login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: User Login
      tags:
      - User Authorzation
  /user/otp:
    get:
      consumes:
      - application/json
      description: Here otp can be checked if true.
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      - description: otp
        in: query
        name: otp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OtpCheckResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Check Otp
      tags:
      - User Authorzation
  /user/profile:
    get:
      consumes:
      - application/json
      description: Here user profile info can be got by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.StandardResponse'
      security:
      - BearerAuth: []
      summary: Get user by key
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
